spring.application.name=AutomatizacionBackend
server.error.whitelabel.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=9091

bridgecore.datasource.jdbc-url=jdbc:oracle:thin:@//172.17.212.224:1527/APPSPRO
bridgecore.datasource.username=USR_VENTA_ENTREGA
bridgecore.datasource.password=Us5_v3nt4_3ntrEg4
bridgecore.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.security.user.name=intclientp01b1
spring.security.user.password=Bccl13ntPrd
spring.security.user.roles=USER
spring.security.headers.frame-options.disable=true
