spring.application.name=AutomatizacionBackend
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
server.error.whitelabel.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=9091

copomex.base-url=https://api.copomex.com
copomex.token=e06e2db6-982a-44f9-86d0-98d749843997

project.remision.path=C:/Users/David Carrillo/Documents/Kv/AutomatizationPython
project.remision.path.pendiente=C:/Users/David Carrillo/Documents/Kv/AutomatizationPython/remisionesAPV/pendiente
python.path=C:/Users/David Carrillo/AppData/Local/Programs/Python/Launcher/py.exe

bridgecore.datasource.jdbc-url=jdbc:oracle:thin:@//172.17.212.224:1527/APPSPRO
bridgecore.datasource.username=USR_VENTA_ENTREGA
bridgecore.datasource.password=Us5_v3nt4_3ntrEg4
bridgecore.datasource.driver-class-name=oracle.jdbc.OracleDriver

bridgecore-qa2.datasource.jdbc-url=jdbc:oracle:thin:@//172.16.212.22:1527/APPSQ
bridgecore-qa2.datasource.username=BRIDGECORE3
bridgecore-qa2.datasource.password=BR1DG3C0R3
bridgecore-qa2.datasource.driver-class-name=oracle.jdbc.OracleDriver

atgcore.datasource.jdbc-url=jdbc:oracle:thin:@//172.17.212.8:1521/atgpro
atgcore.datasource.username=USR_SISTEMAS
atgcore.datasource.password=20160614$1$t3Ma$0p3R4C1oN3$
atgcore.datasource.driver-class-name=oracle.jdbc.OracleDriver
