consulta.obtener-codigos-digitales=SELECT REF_TRANS_ID, \
    COALESCE(JSON_VALUE(RESPONSE_BODY,'$.esdFulfillments.products.tokens.productKey'), '') AS CODIGO, \
    JSON_VALUE(RESPONSE_BODY,'$.description') AS DESCRIPCION, \
    aa.CREATION_DATE, \
    aa.REQUEST_TYPE, \
    aa.ENDPOINT, \
    aa.REQUEST_BODY, \
    aa.RESPONSE_BODY \
    FROM \
    APL_DI.TRANSACTIONS t \
    INNER JOIN \
    APL_DI.AUDIT_ADAPTER aa ON t.ID = aa.ID_TRANSACTION \
    WHERE 1=1 \
    AND t.REF_TRANS_ID IN (:referencias) \
    AND aa.REQUEST_TYPE IN (2, 3) \
    AND COALESCE(JSON_VALUE(RESPONSE_BODY,'$.esdFulfillments.products.tokens.productKey'), '') IS NOT NULL \
    ORDER BY CODIGO ASC

consulta.check-cobro-remision=select tip.pedido, tip.remision from bridgecore.tx tx \
    inner join bridgecore.tx_informacion_procesada tip on tx.id_info_procesada = tip.id \
    where tip.remision in (:remisiones) \
    and tip.id_cat_estatus = 0 \
    and tx.id_tipo_tx = 1

consulta.check-existencia-offerId=select offer_id, leadtime_to_ship from atgcore.mirakl_offer where offer_id in (:offerIds)

consulta.consulta-bridgecore-devolucion-apv=select TIP.remision, tip.fms_trx_id id_cybersource , tip.atg_order_id, \
    tip.atg_ship_grp_id, tip.total_cobrado, SK.SKU_ID, sk.cantidad, dms.total, TIP.FECHA_TX_COMPRA AS fecha_tx_compra, CASE ctt.id --Enviar \
    WHEN 0 THEN 'Dilisa' \
    WHEN 1 THEN 'FF' \
    WHEN 2 THEN 'visa' \
    WHEN 3 THEN 'MasterCard' \
    WHEN 4 THEN 'AMEX' \
    WHEN 6 THEN 'LPC' \
    END as metodoPago, -- ctp.*, \
    dpt.autorizacion_bancaria, tip.is_mkp, dpt.no_tarjeta \
    from BRIDGECORE.TX TX \
    INNER JOIN BRIDGECORE.TX_INFORMACION_PROCESADA TIP ON TX.ID_INFO_PROCESADA = TIP.ID \
    INNER JOIN BRIDGECORE.TX_DETALLE_SKU SK ON TX.ID = SK.TX_ID \
    INNER JOIN BRIDGECORE.TX_DETALLE_MONTO_SKU DMS ON SK.ID = DMS.ID_DETALLE_SKU \
    INNER JOIN BRIDGECORE.TX_INFORMACION_DE_PAGO IP ON TX.ID_INFO_PAGO = IP.ID \
    INNER JOIN BRIDGECORE.TX_DETALLE_PAGO_TARJETA DPT ON IP.ID_TARJETA_DETALLE = DPT.ID \
    INNER JOIN BRIDGECORE.CAT_TIPO_TARJETA CTT ON DPT.ID_TIPO_TARJETA = CTT.ID \
    INNER JOIN BRIDGECORE.CAT_TIPO_DE_PAGO CTP ON TX.ID_TIPO_DE_PAGO = CTP.ID \
    where tip.remision in (:remisiones) \
    and tip.id_cat_estatus = 0 \
    and tx.id_tipo_tx = 1

consulta.cobro=select tx.id, \
    tip.pedido, \
    tip.remision, \
    tip.orden_venta, \
    tip.recognition_store, \
    tip.total_cobrado, \
    tip.id_cat_estatus, \
    tip.terminal, \
    TX.TOTAL_SKUS, \
    TIP.FECHA_TX_COMPRA AS fecha_tx_compra, \
    TIP.atg_ship_grp_id, \
    ta.art_descripcion tipo_articulo, \
    SK.SKU_ID, \
    SK.SECCION, \
    DS.DISPLAY_NAME, \
    SK.PRECIO_VENTA, \
    SK.CANTIDAD, \
    DMS.TOTAL "totalSku", \
    tip.pedido, \
    tip.atg_order_id, \
    DMA.MONTO abono_med, \
    DMC.MONTO cargo_med, \
    DMS.IMPORTE_DESCTO_1ERDIA, \
    DMS.IMPORTE_CON_DESCTO_1ERDIA, \
    DMS.IMPORTE_DESCTO_CASA, \
    DMS.IMPORTE_DESCTO_FIJO, \
    SK.DESCUENTO_PORCENTUAL, \
    SK.ES_FLETE, \
    SK.IS_GIFT \
    from BRIDGECORE.tx TX \
    inner join BRIDGECORE.TX_INFORMACION_PROCESADA TIP ON TX.ID_INFO_PROCESADA = TIP.ID \
    inner join BRIDGECORE.TX_DETALLE_SKU SK ON TX.ID = SK.TX_ID \
    inner JOIN BRIDGECORE.TX_DETALLE_MONTO_SKU DMS ON SK.ID = DMS.ID_DETALLE_SKU \
    LEFT JOIN ATGCATA.DCS_SKU@catalog_link_pro DS ON SK.SKU_ID = DS.SKU_ID \
    LEFT JOIN BRIDGECORE.TX_INFORMACION_DE_PAGO IP ON TX.ID_INFO_PAGO = IP.ID \
    LEFT JOIN BRIDGECORE.TX_DETALLE_MONEDERO_ABONO DMA ON IP.ID_MONEDERO_ABONO_DETALLE = DMA.ID \
    LEFT JOIN BRIDGECORE.TX_DETALLE_MONEDERO_CARGO DMC ON IP.ID_MONEDERO_CARGO_DETALLE = DMC.ID \
    LEFT JOIN BRIDGECORE.CAT_TIPO_DE_PAGO CTP ON TX.ID_TIPO_DE_PAGO = CTP.ID \
    left JOIN BRIDGECORE.cat_tipo_articulo ta ON TX.id_tipo_articulo = ta.id \
    where TIP.atg_ship_grp_id IN (:atgShipGrpIds) \
    and tip.atg_order_id IN (:atgOrderIds) \
    and TIP.ID_CAT_ESTATUS = 0 \
    and TX.ID_TIPO_TX = 1
