consulta.obtener-codigos-digitales=SELECT REF_TRANS_ID, \
    COALESCE(JSON_VALUE(RESPONSE_BODY,'$.esdFulfillments.products.tokens.productKey'), '') AS CODIGO, \
    JSON_VALUE(RESPONSE_BODY,'$.description') AS DESCRIPCION, \
    aa.CREATION_DATE, \
    aa.REQUEST_TYPE, \
    aa.ENDPOINT, \
    aa.REQUEST_BODY, \
    aa.RESPONSE_BODY \
    FROM \
    APL_DI.TRANSACTIONS t \
    INNER JOIN \
    APL_DI.AUDIT_ADAPTER aa ON t.ID = aa.ID_TRANSACTION \
    WHERE 1=1 \
    AND t.REF_TRANS_ID IN (:referencias) \
    AND aa.REQUEST_TYPE IN (2, 3) \
    AND COALESCE(JSON_VALUE(RESPONSE_BODY,'$.esdFulfillments.products.tokens.productKey'), '') IS NOT NULL \
    ORDER BY CODIGO ASC
